### PR TITLE
Prototype 2x2 matmul function to be compiled.

### LINKED ISSUE #113: Make model compilation work
## Motivations

PyTorch 2.0 provides a [compilation routine](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html) that JIT-compile PyTorch code into optimized kernels, similarly to what Jax does. This is a very simple way to significantly speed up PyTorch code. However, currently the `torch.compile` routine does not have support for complex numbers and it cannot be applied directly to PyQTorch.

## Proposal

In order to be able to use `torch.compile` with models created using PyQTorch, we should remove complex numbers from the library. The fastest way to do so is to split real and imaginary parts of the wavefunction into two real-valued tensors which are treated separately in the computation and put together only when requested.

To keep in mind:
- [x] make real/imaginary parts separation
- [x] implement simple interface to allow for compilation, user should not be involved ideally
  - [x] Implemented, compiled and benchmarked for 2x2 matmuls and 2x2 matvecmuls
  - [ ] Implemented, compiled and benchmarked for tensordots
  - [ ] Implemented, compiled and benchmarked for einsum
- [x] benchmark implementation with current complex-value approach
- [ ] remove the whole complex-valued code if performance is acceptable, otherwise maintain it alongside the real-valued one

### PR DESCRIPTION
**Pull request by Roland-djee**
Fixes #113.

### CODE REVIEW

**Comment by Roland-djee** [comment]
> Hey @dominikandreasseitz. Here is a prototype for a 2x2 matrix matmul by separating real/imag parts. Question: does it work straight out of the box for you ? I've got clang warnings that it doesn't find `torch/include`.

OK I could make it work in a conda env.

**Comment by dominikandreasseitz** [comment]
great, lets try with tensordot and 2qubit gates

**Comment by nmheim** [comment]
Maybe it makes sense to look at what’s done here https://github.com/albanD/subclass_zoo/blob/main/complex_tensor.py

**Comment by Roland-djee** [comment]
@dominikandreasseitz closing as stale for too long.

**Pull request closed without merging**
